- CONTRIBUTING.md
- README.md
> Fixed mailto and links in README.md

- .gitmodules
> Adding git submodule for safe string library

- source/octf/cli/cmd/CommandProtobuf.cpp
- source/octf/trace/parser/TraceEventHandlerJsonPrinter.h
> Fixes compilation on Ubuntu 18

- setup_dependencies.sh
> Fixes setup dependencies script for centos

- source/octf/trace/trace.c
> Updates include path for trace kernel case

- source/CMakeLists.txt
> Added ldconfig step to install target

- source/octf/trace/parser/TraceFileReader.cpp
- source/octf/trace/parser/TraceFileReader.h
> Fixes parsing empty trace file

- source/octf/cli/param/Parameter.cpp
- source/octf/cli/param/Parameter.h
- source/octf/interface/internal/TraceJob.cpp
- source/octf/interface/internal/TraceJob.h
- source/octf/node/NodeBase.h
- source/octf/node/NodeGeneric.cpp
- source/octf/node/NodeGeneric.h
- source/octf/node/NodeShadow.h
> Further fixes after static code analysis

- source/octf/utils/SignalHandler.cpp
- source/octf/utils/SignalHandler.h
Allows to send any signal from application. Previously it was possible
to send SIGUSR1 only.
> Updates signal handler

- source/octf/utils/Exception.cpp
> Removes not needed include in exception

- source/octf/interface/TraceManager.cpp
> Fixes negative trace duration in summary when an error occurred

- source/octf/utils/FileOperations.cpp
> Fixes segment fault when creating directory for relative path

- source/octf/interface/TraceManager.cpp
> Checks if trace dir is accessible before starting tracing

- source/octf/interface/InterfaceTraceManagementImpl.cpp
- source/octf/interface/InterfaceTraceManagementImpl.h
- source/octf/proto/InterfaceTraceManagement.proto
In case of inconsistent state user shall be able to enforce removing traces.
> Adds force flag to enforce remove a trace

- source/octf/socket/internal/unixsocket/Server.cpp
> Fix for properly closing socket in Server class

- source/octf/node/NodeBase.cpp
- source/octf/node/NodeBase.h
> Unified naming of node's settings

- source/octf/node/NodeBase.cpp
- source/octf/utils/ProtobufReaderWriter.cpp
- source/octf/utils/ProtobufReaderWriter.h
> Avoiding TOCTOU vulnerability in ProtobufReaderWriter class

- source/octf/proto/InterfaceTraceManagement.proto
- source/octf/proto/InterfaceTraceParsing.proto
- source/octf/proto/traceDefinitions.proto
> Adds short key to path cli switch

- source/CMakeLists.txt
> Fixes installation requires additional 'ldconfig'

- source/octf/utils/ProtobufReaderWriter.cpp
> Fix for bug in opening file in ProtobufReaderWriter class

- source/octf/utils/FileOperations.cpp
- source/octf/utils/FileOperations.h
> Removed redundant code and added notes about TOCTOU vulnerability.

- source/octf/cli/CLIList.cpp
- source/octf/cli/CLIList.h
- source/octf/cli/Executor.cpp
- source/octf/cli/Executor.h
- source/octf/cli/cmd/Command.cpp
> CLI execute method now returns a boolean value. CLI exceptions are printed to stderr

- source/octf/utils/ProtobufReaderWriter.cpp
- source/octf/utils/ProtobufReaderWriter.h
> Updates protobuf reader writer

- source/octf/interface/TraceConverter.cpp
- source/octf/interface/TraceConverter.h
> Improves trace serialization

- source/octf/trace/parser/TraceFileReader.cpp
> Updates error message

- setup_dependencies.sh
> Updates setup dependencies

- source/octf/utils/ProtobufReaderWriter.cpp
> Fixed bug in make read only method

- source/octf/trace/parser/TraceFileParser.cpp
> Fixed parser not printing last events

- doc/CMakeLists.txt
> Sets main page in doxygen

- source/octf/proto/InterfaceTraceManagement.proto
> Updates interface trace management proto

- source/octf/cli/Executor.cpp
> Clenups printing of help and error in executor

- source/octf/utils/container/IContainer.h
> Adds missing includes in container interface header

- source/octf/interface/TraceConverter.cpp
- source/octf/interface/TraceConverter.h
- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
> Extends IO traces by completion

- doc/coding_style/CODING_STYLE.md
- doc/coding_style/CodingStyle.cpp
> Updated coding style rules regarding TODO

- source/octf/trace/parser/ITraceParser.h
- source/octf/trace/parser/IoTraceEventHandlerCsvPriner.h
- source/octf/trace/parser/IoTraceEventHandlerJsonPrinter.h
- source/octf/trace/parser/TraceEventHandlerCsvPrinter.h
- source/octf/trace/parser/TraceFileParser.h
- source/octf/utils/table/Table.cpp
- source/octf/utils/table/Table.h
- source/octf/utils/table/Types.h
- source/octf/utils/table/internal/TableMap.h
> Extends CSV by complex types (oneof, map, repeated)

- source/octf/proto/opts.proto
> Cleanups CLI options proto definition

- tools/coding_style/pre-commit.sh
> Updates pre-commit hook

- source/octf/trace/trace.c
- source/octf/trace/trace.h
> Adds new function to circular buffer

- source/octf/c/iotrace_plugin.cpp
> Fixes compilation error on CentOS7

- source/octf/interface/InterfaceTraceCreatingImpl.cpp
- source/octf/interface/InterfaceTraceManagementImpl.cpp
- source/octf/interface/TraceManager.cpp
- source/octf/interface/TraceManager.h
- source/octf/proto/InterfaceTraceCreating.proto
- source/octf/proto/traceDefinitions.proto
> Allows define a label for IO trace

- source/octf/utils/ProtobufReaderWriter.cpp
> Allow forward compability when reading protobuf json files

- source/octf/interface/TraceConverter.cpp
- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/ParsedIoTraceEventHandler.h
> Fixes printing queue depth in IO trace

- source/octf/communication/CMakeLists.txt
- source/octf/communication/RpcControllerImpl.cpp
- source/octf/communication/RpcControllerImpl.h
- source/octf/communication/RpcOutputStream.cpp
- source/octf/communication/RpcOutputStream.h
- source/octf/utils/Log.cpp
- source/octf/utils/Log.h
> Provides RPC output stream

- source/octf/analytics/statistics/Distribution.cpp
- source/octf/analytics/statistics/Distribution.h
- source/octf/analytics/statistics/IoStatistics.cpp
- source/octf/analytics/statistics/IoStatistics.h
- source/octf/analytics/statistics/IoStatisticsSet.cpp
- source/octf/analytics/statistics/IoStatisticsSet.h
- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/interface/InterfaceTraceParsingImpl.h
- source/octf/proto/InterfaceTraceParsing.proto
- source/octf/proto/statistics.proto
- source/octf/utils/table/Row.cpp
- source/octf/utils/table/Row.h
> Extends IO statistics by percentiles and histogram

- source/octf/trace/parser/CMakeLists.txt
- source/octf/trace/parser/TraceEventHandlerWorkset.cpp
- source/octf/trace/parser/TraceEventHandlerWorkset.h
> Added handler for workset calculator

- source/octf/interface/TraceConverter.cpp
- source/octf/interface/TraceConverter.h
- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
> Extends IO traces by file name

- source/octf/proto/parsedTrace.proto
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/ParsedIoTraceEventHandler.h
> Prints file path when parsing IO trace

- source/octf/trace/parser/CMakeLists.txt
- source/octf/trace/parser/HandlerRunner.h
- source/octf/trace/parser/TraceEventHandler.h
> Added handler runner class

- source/octf/analytics/statistics/WorksetCalculator.cpp
- source/octf/analytics/statistics/WorksetCalculator.h
> Added move constructor to WorksetCalculator

- source/octf/trace/parser/TraceFileParser.cpp
> Updated reset of trace parser

- source/octf/analytics/statistics/IoStatistics.cpp
- source/octf/analytics/statistics/IoStatistics.h
- source/octf/analytics/statistics/IoStatisticsSet.cpp
- source/octf/analytics/statistics/IoStatisticsSet.h
- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/interface/InterfaceTraceParsingImpl.h
- source/octf/proto/InterfaceTraceParsing.proto
- source/octf/trace/parser/ParsedIoTraceEventHandlerStatistics.h
> Added LBA hits histogram

- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/interface/InterfaceTraceParsingImpl.h
- source/octf/utils/table/Table.h
> Changed the structure of CSV output for histograms

- source/CMakeLists.txt
> Added static version of octf library to build system

- source/CMakeLists.txt
> Updates CMake for static library target

- source/octf/analytics/statistics/IoStatistics.cpp
> Fixed enabling lba histogram

- source/octf/cli/Executor.cpp
- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/proto/InterfaceTraceParsing.proto
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/ParsedIoTraceEventHandler.h
- source/octf/trace/parser/ParsedIoTraceEventHandlerStatistics.h
Moved exception handling out of Executor
> Added exclusive range parameters to lba histogram

- setup_dependencies.sh
> Added git to list of dependencies in setup script

- setup_dependencies.sh
> Added fedora to setup dependencies script

- source/octf/interface/TraceConverter.cpp
- source/octf/interface/TraceConverter.h
- source/octf/proto/parsedTrace.proto
- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
> Tracing of filesystem events

- source/octf/analytics/statistics/FilesystemStatistics.cpp
- source/octf/interface/TraceConverter.cpp
- source/octf/proto/parsedTrace.proto
- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/ParsedIoTraceEventHandler.h
- source/octf/trace/parser/ParsedIoTraceEventHandlerPrinter.cpp
- source/octf/trace/parser/TraceEventHandlerFilesystemStatistics.cpp
> Cleans parsed trace output

- source/octf/analytics/statistics/FilesystemStatistics.cpp
- source/octf/analytics/statistics/FilesystemStatistics.h
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/ParsedIoTraceEventHandler.h
> Updates filesystem statistics

- source/octf/trace/trace.c
- source/octf/trace/trace.h
- tests/octf/trace/TracingTest.cpp
> Add zero copy mechanism for inserting entries into trace buffer

- source/octf/interface/internal/TraceJob.cpp
- source/octf/trace/trace.c
- source/octf/trace/trace.h
- tests/octf/trace/TracingTest.cpp
> Add zero copy mechanism for reading entries from trace buffer

- octf-paths.cmake
> Removed invalid extra comma in JSON config

- source/octf/analytics/statistics/FilesystemStatistics.cpp
- source/octf/analytics/statistics/IFileSystemViewer.h
- source/octf/proto/statistics.proto
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
> Replaces file basename by file name prefix

- source/octf/trace/parser/TraceFileReader.cpp
> Fixed message size check in TraceFileReader

- source/octf/utils/CMakeLists.txt
- source/octf/utils/Exception.h
- source/octf/utils/ShellExecutor.cpp
- source/octf/utils/ShellExecutor.h
> Added shell executor class

- source/octf/utils/CMakeLists.txt
- source/octf/utils/CsvParser.cpp
- source/octf/utils/CsvParser.h
- source/octf/utils/table/Cell.h
- source/octf/utils/table/internal/TableMap.cpp
> Added CSV parser class, fixed table::Cell minor bug

- source/examples/plugin/client/TestPluginShadow.cpp
- source/octf/trace/parser/CMakeLists.txt
- source/octf/trace/parser/ITraceParser.h
- source/octf/trace/parser/ParsedIoTraceEventQueue.cpp
- source/octf/trace/parser/ParsedIoTraceEventQueue.h
- source/octf/trace/parser/TraceEventHandler.h
- source/octf/trace/parser/TraceFileParser.cpp
- source/octf/trace/parser/TraceFileParser.h
- source/octf/trace/parser/TraceFileReader.cpp
- source/octf/trace/parser/TraceFileReader.h
- source/octf/utils/Exception.cpp
- source/octf/utils/Exception.h
- tests/octf/CMakeLists.txt
- tests/octf/UtilsTest.h
- tests/octf/trace/CMakeLists.txt
- tests/octf/trace/TraceUtilsTest.h
- tests/octf/trace/parser/CMakeLists.txt
- tests/octf/trace/parser/ParsedIoTraceEventQueueTest.cpp
> Adds parsed IO queue

- .gitmodules
- CMakeLists.txt
- setup_dependencies.sh
- source/CMakeLists.txt
- source/examples/auto_cli/CMakeLists.txt
- source/third_party/CMakeLists.txt
- source/third_party/octf-protobuf.cmake
- source/third_party/octf-safestringlib.cmake
- tests/CMakeLists.txt
> Add protobuf as submodule, built and linked as a static library.

- source/examples/CMakeLists.txt
- source/octf/cli/Executor.cpp
- source/octf/cli/Executor.h
- source/octf/cli/internal/CLIUtils.cpp
- source/octf/cli/internal/CLIUtils.h
- source/octf/cli/internal/CommandSet.cpp
- source/octf/cli/internal/CommandSet.h
- source/octf/cli/internal/Module.cpp
- source/octf/cli/internal/Module.h
- source/octf/cli/internal/cmd/CmdHelp.cpp
- source/octf/cli/internal/cmd/CmdVersion.cpp
- source/octf/proto/InterfaceConfiguration.proto
- source/octf/proto/InterfaceTraceManagement.proto
- source/octf/proto/InterfaceTraceParsing.proto
- source/octf/proto/opts.proto
> Reorganizes CLI shorts and long keys

- setup_dependencies.sh
Also Centos was potentially missing wget package
> Add missing -p parameter for cmake setup

- Makefile
- source/CMakeLists.txt
> Build system update for rpm build

- setup_dependencies.sh
> Updates setup dependencies script

- octf-paths.cmake
- tools/installer/installation_config.cmake
> Publishes cmake vars of OCTF config file

- source/octf/analytics/statistics/IoStatistics.cpp
- source/octf/analytics/statistics/IoStatisticsSet.cpp
- source/octf/analytics/statistics/IoStatisticsSet.h
- source/octf/interface/InterfaceTraceParsingImpl.cpp
> Prints all fields in statistics

- source/octf/proto/InterfaceTraceParsing.proto
> Updates CLI interface of trace parsing

- doc/NOTICE
> Updated NOTICE

- setup_dependencies.sh
> Add support for Centos/RedHat 8

- source/examples/plugin/proto/CMakeLists.txt
> Fixed occasional include errors during octf build

- source/octf/cli/Executor.cpp
- source/octf/cli/Executor.h
- source/octf/cli/internal/CommandSet.cpp
> Avoids CLI key duplication in executor

- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
> Add handling of potentially dropped submission IOs

- setup_dependencies.sh
> Fixes detecting RHEL8 distro in setup dependencies script

- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
> Made meaningful enums be non-zero to allow printing them

- octf-version.cmake
> Add handling of label version from outside file

- source/octf/interface/InterfaceTraceCreatingImpl.cpp
- source/octf/interface/TraceManager.cpp
- source/octf/interface/internal/TraceJob.cpp
- source/octf/node/NodeBase.cpp
> Added catch blocks for standard exceptions where needed

- source/octf/analytics/statistics/IoStatistics.cpp
> Fix handling of workset content for discard requests

- setup_dependencies.sh
> Dont prints info to stderr in setup_dependencies.sh

- source/octf/c/iotrace_plugin.cpp
> Fix potential nullptr dereference

- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
> Fix case label using other enum than the rest

- source/octf/utils/table/Table.cpp
> Fix various potential nullptr dereferences

- source/octf/interface/InterfaceTraceCreatingImpl.cpp
> Fix potential nullptr dereference while validating parameters

- source/octf/utils/table/Cell.h
> Add assignment operator to Data class

- source/octf/interface/TraceManager.cpp
- source/octf/interface/internal/TraceJob.cpp
> Reduces log messages during tracing

- source/octf/analytics/statistics/WorksetCalculator.cpp
> Fixes arithmetic underflow in working set calculator

- source/octf/trace/trace.c
> Implement security review findings

- source/octf/trace/parser/HandlerRunner.h
> Fixes compilation problems of handler runner for centos7

- setup_dependencies.sh
- source/examples/plugin/proto/CMakeLists.txt
- tools/scripts/octf-common.sh
- tools/scripts/octf-setup-cmake.sh
> Updates script of setup dependencies

- source/octf/trace/trace.c
> Remove warning when closing already closed trace

- source/octf/interface/InterfaceTraceManagementImpl.cpp
- source/octf/interface/InterfaceTraceManagementImpl.h
- source/octf/trace/CMakeLists.txt
- source/octf/trace/ITrace.h
- source/octf/trace/ITraceRepository.h
- source/octf/trace/TraceLibrary.cpp
- source/octf/trace/TraceLibrary.h
- source/octf/trace/internal/CMakeLists.txt
- source/octf/trace/internal/TraceBase.cpp
- source/octf/trace/internal/TraceBase.h
- source/octf/trace/internal/TraceLocal.cpp
- source/octf/trace/internal/TraceLocal.h
- source/octf/trace/internal/TraceRepositoryLocal.cpp
- source/octf/trace/internal/TraceRepositoryLocal.h
> Add trace abstraction, repository, and library

- source/octf/cli/internal/param/ParamString.cpp
- source/octf/cli/internal/param/ParamString.h
- source/octf/proto/opts.proto
> Updates CLI string parameter

- source/octf/cli/internal/param/ParamString.cpp
> Fix reversed logic when dealing with limit of multiple value params

- source/octf/interface/TraceConverter.cpp
- source/octf/proto/parsedTrace.proto
- source/octf/proto/trace.proto
- source/octf/trace/iotrace_event.h
- source/octf/trace/parser/v1/ParsedIoTraceEventHandler.cpp
> Add device model to device description

- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/interface/InterfaceTraceParsingImpl.h
- source/octf/proto/InterfaceTraceParsing.proto
- source/octf/trace/parser/CMakeLists.txt
- source/octf/trace/parser/TraceEventHandlerDevicesList.cpp
- source/octf/trace/parser/TraceEventHandlerDevicesList.h
> Add device list parser

- source/octf/analytics/statistics/Distribution.cpp
This patch should fix the calculation of sector/latency percentile
calculation, where:
a) Sectors would be have value offset by value 0.5
b) Higher percentiles would be calculated using wrong/empty buckets
> Fix percentile calculation distribution

- source/octf/analytics/statistics/IoStatisticsSet.cpp
> Add device model to statistics output

- source/octf/analytics/statistics/IoStatistics.cpp
- source/octf/analytics/statistics/IoStatistics.h
- source/octf/analytics/statistics/IoStatisticsSet.cpp
- source/octf/analytics/statistics/IoStatisticsSet.h
- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/interface/InterfaceTraceParsingImpl.h
- source/octf/proto/InterfaceTraceParsing.proto
> Add io size histogram

- source/octf/interface/internal/IoTraceParser.h
- source/octf/trace/parser/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/ParsedIoTraceEventHandler.h
> Add parser init/deinit functions to IoTraceParser

- setup_dependencies.sh
- tools/scripts/octf-common.sh
> Add Debian build support

- source/octf/analytics/statistics/IoStatistics.cpp
- source/octf/analytics/statistics/IoStatistics.h
- source/octf/analytics/statistics/IoStatisticsSet.cpp
- source/octf/analytics/statistics/IoStatisticsSet.h
- source/octf/interface/InterfaceTraceParsingImpl.cpp
- source/octf/interface/InterfaceTraceParsingImpl.h
- source/octf/proto/InterfaceTraceParsing.proto
> Add qd histogram

- source/octf/trace/parser/v1/ParsedIoTraceEventHandler.cpp
- source/octf/trace/parser/v1/ParsedIoTraceEventHandler.h
Dropped submission requests shouldn't disturb QD calculation as much.
> Update handling of QD for dropped requests

- source/octf/cli/internal/cmd/CommandProtobuf.cpp
- source/octf/cli/internal/cmd/CommandProtobufLocal.cpp
- source/octf/cli/internal/param/CMakeLists.txt
- source/octf/cli/internal/param/ParamDouble.cpp
- source/octf/cli/internal/param/ParamDouble.h
- source/octf/proto/opts.proto
Signed-off-by: Kozlowski Mateusz <mateusz.kozlowski@intel.com>
> Add Double parameter to CLI

- source/octf/utils/table/Addr.h
- source/octf/utils/table/CMakeLists.txt
- source/octf/utils/table/Cell.h
- source/octf/utils/table/Column.cpp
- source/octf/utils/table/Column.h
- source/octf/utils/table/ISet.h
- source/octf/utils/table/Iterators.cpp
- source/octf/utils/table/Iterators.h
- source/octf/utils/table/Properties.cpp
- source/octf/utils/table/Properties.h
- source/octf/utils/table/Row.cpp
- source/octf/utils/table/Row.h
- source/octf/utils/table/Set.cpp
- source/octf/utils/table/Set.h
- source/octf/utils/table/Table.cpp
- source/octf/utils/table/Table.h
- source/octf/utils/table/Types.h
- source/octf/utils/table/internal/TableMap.cpp
- source/octf/utils/table/internal/TableMap.h
> Defines table format properties

- source/octf/utils/CMakeLists.txt
- source/octf/utils/ProtobufReflection.cpp
- source/octf/utils/ProtobufReflection.h
> Initial version of protocol buffer message and description reflection
